import type { MetadataRoute } from "next";

import { buildSitemap } from "@/lib/site-routes.js";

/**
 * sitemap.xml (S5-002) — the twelve public docs routes, generated by the
 * typed buildSitemap model (src/lib/site-routes.ts). The route is
 * statically prerendered, so `lastModified` is the build timestamp; the
 * canonical base defaults to the production deployment and is overridable
 * via NEXT_PUBLIC_SITE_URL (see resolveSiteUrl).
 */
export default function sitemap(): MetadataRoute.Sitemap {
  return buildSitemap();
}
