import type { MetadataRoute } from "next";

import { buildRobots } from "@/lib/site-routes";

/**
 * robots.txt (S5-001) — a public site: every crawler may fetch everything,
 * nothing is disallowed, and the sitemap is referenced. Generated by the
 * typed buildRobots model (src/lib/site-routes.ts); the base URL follows
 * the same NEXT_PUBLIC_SITE_URL override as the sitemap.
 */
export default function robots(): MetadataRoute.Robots {
  return buildRobots();
}
